### ISSUE TITLE
`binh_rows` and 'downloadModule`

### ISSUE THREAD

**Issue by AmirHKiani98** [PredictiveEcology/SpaDES-modules#35]
I've been having a few issues with this package lately:
- 1- the first one is, after using `downloadModule`  the rstudio malfunctions and uses 5 GB of the RAM. is this function expected to use this huge amount of ram?
- 2- the next one is, after downloading `caribouMovementLcc` and `LCC2005` manually and running the example code in rstudio which exists in [this link](https://github.com/PredictiveEcology/SpaDES-modules/blob/master/modules/LCC2005/LCC2005.Rmd), I got this error
`
Error in binh_rows(createsOutput("caribou", "SpatialPointsDataFrame",  : 
  could not find function "binh_rows"
`
I think the `binh_rows` supposed to be `bind_rows`. is that right?

**Comment by achubaty** [comment]
That's correct -- should have be `bind_rows` (but that requires `dplyr` be loaded). However, modules should be run using newer versions of `SpaDES.core`, which has the `bindrows`, which is prefered.

**Comment by achubaty** [comment]
fixed in https://github.com/PredictiveEcology/SpaDES-modules/commit/0043d39efd62c1a5198a21032bf8cc7049800422
