### ISSUE TITLE
update modules to use P() instead of p()

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES-modules#9]
- [x] all LCC2005 modules need to be updated
- [ ] others?

**Comment by achubaty** [comment]
* fireSpreadLcc updated in 06d16c83487bde8f83a84c0ca307dfc6742f1907 and c50f4dcdd9fd771ee916b595d799976ffe4e618c
* cropReprojectLccAge updated in 06d16c83487bde8f83a84c0ca307dfc6742f1907

**Comment by achubaty** [comment]
@CeresBarros want to take a look at this and confirm it's been done?

**Comment by CeresBarros** [comment]
didn't find any p() 's in the modules. So it seems to be fixed
